import type { MetadataRoute } from "next";

/**
 * Web app manifest, generated by Next.js's metadata API and served
 * at `/manifest.webmanifest`. Lets visitors install Nexplay as an
 * app on phones (iOS / Android) and Chromium-based desktops via
 * "Add to Home Screen" / "Install".
 *
 * Without a service worker we're not a *full* PWA (no offline
 * support), but iOS Safari and modern Chromium both honour the
 * manifest's icon + theme metadata for the standalone shell, which
 * is the main thing users notice.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Nexplay — Play free games online",
    short_name: "Nexplay",
    description:
      "Free browser games. Play solo, climb the leaderboards, or invite friends to play live.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    background_color: "#0a0c14",
    theme_color: "#7c5cff",
    orientation: "any",
    categories: ["games", "entertainment"],
    icons: [
      // Same 2000px asset declared at several sizes — browsers pick
      // the closest match and downscale. The `purpose: "any maskable"`
      // entry lets Android crop the icon into adaptive shapes
      // (circle / squircle / etc.) without it looking weird.
      {
        src: "/nexplay-icon.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/nexplay-icon.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/nexplay-icon.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
