import type { MetadataRoute } from "next";

/**
 * Web app manifest, generated by Next.js's metadata API and served
 * at `/manifest.webmanifest`. Lets visitors install Nexplay as an
 * app on phones (iOS / Android) and Chromium-based desktops via
 * "Add to Home Screen" / "Install".
 *
 * Without a service worker we're not a *full* PWA (no offline
 * support), but iOS Safari and modern Chromium both honour the
 * manifest's icon + theme metadata for the standalone shell, which
 * is the main thing users notice.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Nexplay — Play free games online",
    short_name: "Nexplay",
    description:
      "Free browser games. Play solo, climb the leaderboards, or invite friends to play live.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    background_color: "#0a0c14",
    theme_color: "#7c5cff",
    orientation: "any",
    categories: ["games", "entertainment"],
    icons: [
      // Properly-sized PNGs per declared dimension. Browsers pick the
      // closest match. The `purpose: "maskable"` entry lets Android
      // crop into adaptive shapes (circle / squircle / etc.) without
      // looking weird.
      {
        src: "/nexplay-icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/nexplay-icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/nexplay-icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
