import type { Category, Game } from "./types";

export const CATEGORIES: Category[] = [
  {
    slug: "action",
    title: "Action",
    emoji: "⚔️",
    description: "Fast-paced reflex challenges and combat games.",
  },
  {
    slug: "puzzle",
    title: "Puzzle",
    emoji: "🧩",
    description: "Brain-bending puzzles and logic games.",
  },
  {
    slug: "arcade",
    title: "Arcade",
    emoji: "🕹️",
    description: "Classic and modern arcade hits.",
  },
  {
    slug: "racing",
    title: "Racing",
    emoji: "🏎️",
    description: "Speed, drift, and outrun the competition.",
  },
  {
    slug: "2-player",
    title: "2 Player",
    emoji: "👥",
    description: "Play head-to-head with a friend.",
  },
  {
    slug: "sports",
    title: "Sports",
    emoji: "⚽",
    description: "Score goals, slam dunks, and home runs.",
  },
  {
    slug: "strategy",
    title: "Strategy",
    emoji: "♟️",
    description: "Outsmart opponents with planning and tactics.",
  },
  {
    slug: "adventure",
    title: "Adventure",
    emoji: "🗺️",
    description: "Explore worlds, solve quests, find treasure.",
  },
];

export const GAMES: Game[] = [
  {
    slug: "tic-tac-toe",
    icon: "game-icons:tic-tac-toe",
    title: "Tic-Tac-Toe",
    short: "Classic 3-in-a-row, online with friends.",
    description:
      "The timeless paper-and-pencil game, now playable online with anyone in the world. Quick, simple, endlessly fun.",
    categories: ["2-player", "strategy", "puzzle"],
    tags: ["multiplayer", "classic", "quick"],
    gradient: "linear-gradient(135deg, #7c5cff 0%, #ff5cae 100%)",
    glyph: "❌⭕",
    source: "custom",
    controls: ["Mouse", "Touch"],
    players: "both",
    featured: true,
    isNew: true,
    rating: 4.6,
    plays: 12_400,
  },
  {
    slug: "snake",
    icon: "game-icons:snake",
    title: "Snake",
    short: "Eat, grow, don't bite yourself.",
    description:
      "The arcade classic. Guide your snake to collect food and grow as long as you can without crashing.",
    categories: ["arcade", "action"],
    tags: ["classic", "highscore", "single-player"],
    gradient: "linear-gradient(135deg, #16a34a 0%, #65a30d 100%)",
    glyph: "🐍",
    source: "custom",
    controls: ["Arrow Keys", "WASD", "Touch"],
    players: "single",
    featured: true,
    rating: 4.5,
    plays: 28_900,
  },
  {
    slug: "2048",
    icon: "game-icons:cubes",
    title: "2048",
    short: "Combine tiles, reach 2048.",
    description:
      "Slide numbered tiles to merge them. Reach 2048 — or aim higher. Devilishly addictive.",
    categories: ["puzzle"],
    tags: ["numbers", "highscore", "single-player"],
    gradient: "linear-gradient(135deg, #f59e0b 0%, #ef4444 100%)",
    glyph: "🔢",
    source: "custom",
    controls: ["Arrow Keys", "Swipe"],
    players: "single",
    featured: true,
    rating: 4.7,
    plays: 45_300,
  },
  {
    slug: "connect-four",
    icon: "game-icons:disc",
    title: "Connect Four",
    short: "Drop, line up four, win.",
    description:
      "The vertical strategy classic. Drop your discs and connect four in a row before your opponent does.",
    categories: ["2-player", "strategy"],
    tags: ["multiplayer", "classic"],
    gradient: "linear-gradient(135deg, #ef4444 0%, #f59e0b 100%)",
    glyph: "🔴",
    source: "custom",
    controls: ["Mouse", "Touch"],
    players: "both",
    isNew: true,
    rating: 4.4,
    plays: 8_700,
  },
  {
    slug: "pong",
    icon: "game-icons:tennis-ball",
    title: "Pong",
    short: "The original — paddle vs paddle.",
    description:
      "The game that started it all. Hit the ball past your opponent's paddle to score.",
    categories: ["2-player", "arcade", "sports"],
    tags: ["classic", "multiplayer"],
    gradient: "linear-gradient(135deg, #1f2937 0%, #374151 100%)",
    glyph: "🏓",
    source: "custom",
    controls: ["W/S", "Arrow Keys"],
    players: "both",
    rating: 4.3,
    plays: 6_500,
  },
  {
    slug: "memory-match",
    icon: "game-icons:brain",
    title: "Memory Match",
    short: "Find the pairs, beat the clock.",
    description:
      "Flip cards to find matching pairs. Train your memory and rack up the highest score.",
    categories: ["puzzle"],
    tags: ["memory", "single-player", "casual"],
    gradient: "linear-gradient(135deg, #06b6d4 0%, #3b82f6 100%)",
    glyph: "🧠",
    source: "custom",
    controls: ["Mouse", "Touch"],
    players: "single",
    rating: 4.2,
    plays: 11_200,
  },
  {
    slug: "flappy",
    icon: "game-icons:hummingbird",
    title: "Flappy",
    short: "Tap to flap. Don't crash.",
    description:
      "The notoriously difficult one-button arcade game. How far can you fly?",
    categories: ["arcade", "action"],
    tags: ["highscore", "single-player", "hard"],
    gradient: "linear-gradient(135deg, #facc15 0%, #16a34a 100%)",
    glyph: "🐦",
    source: "custom",
    controls: ["Space", "Tap"],
    players: "single",
    isNew: true,
    rating: 4.0,
    plays: 19_800,
  },
  {
    slug: "hextris",
    icon: "game-icons:honeycomb",
    title: "Hextris",
    short: "Spin the hex, line up colours, survive the rain.",
    description:
      "Coloured blocks slide in from six lanes toward a central hexagon. Rotate the hex to redirect them, line up three of a kind on a face — or around a ring — to clear them. Cascading clears score big. Stack reaches the danger ring and it's over.",
    categories: ["puzzle", "arcade"],
    tags: ["puzzle", "highscore", "single-player"],
    gradient: "linear-gradient(135deg, #7c5cff 0%, #ff5cae 100%)",
    glyph: "⬢",
    source: "custom",
    controls: ["Arrow Keys", "WASD", "Touch"],
    players: "single",
    isNew: true,
    rating: 4.5,
    plays: 22_100,
  },
  {
    slug: "neon-runner",
    icon: "game-icons:running-shoe",
    title: "Neon Runner",
    short: "Endless runner through neon worlds.",
    description:
      "Run, jump, slide. Dodge obstacles in a procedurally generated neon city.",
    categories: ["action", "arcade"],
    tags: ["endless", "single-player"],
    gradient: "linear-gradient(135deg, #8b5cf6 0%, #06b6d4 100%)",
    glyph: "🏃",
    source: "custom",
    controls: ["Space", "Arrow Keys"],
    players: "single",
    rating: 4.1,
    plays: 4_300,
  },
  {
    slug: "drift-king",
    icon: "game-icons:f1-car",
    title: "Drift King",
    short: "Top-down arcade racing & drifting.",
    description:
      "Master the corners with realistic drift physics. Climb the leaderboard.",
    categories: ["racing", "action"],
    tags: ["racing", "highscore"],
    gradient: "linear-gradient(135deg, #dc2626 0%, #1f2937 100%)",
    glyph: "🏎️",
    source: "custom",
    controls: ["Arrow Keys", "WASD"],
    players: "single",
    rating: 4.3,
    plays: 7_800,
  },
  {
    slug: "checkers",
    icon: "game-icons:chess-pawn",
    title: "Checkers",
    short: "Hop, capture, become king.",
    description:
      "Classic checkers / draughts. Play locally with a friend or challenge an opponent online.",
    categories: ["2-player", "strategy"],
    tags: ["classic", "multiplayer", "board"],
    gradient: "linear-gradient(135deg, #b91c1c 0%, #1f2937 100%)",
    glyph: "♟️",
    source: "custom",
    controls: ["Mouse", "Touch"],
    players: "both",
    rating: 4.2,
    plays: 5_900,
  },
  {
    slug: "treasure-hunt",
    icon: "game-icons:treasure-map",
    title: "Treasure Hunt",
    short: "Top-down adventure & exploration.",
    description:
      "Explore caves, solve puzzles, and uncover ancient treasures in this top-down adventure.",
    categories: ["adventure", "puzzle"],
    tags: ["exploration", "single-player"],
    gradient: "linear-gradient(135deg, #ca8a04 0%, #16a34a 100%)",
    glyph: "🗝️",
    source: "custom",
    controls: ["WASD", "Arrow Keys"],
    players: "single",
    rating: 4.0,
    plays: 3_400,
  },
  {
    slug: "tetris",
    icon: "game-icons:brick-pile",
    title: "Tetris",
    short: "Stack the falling blocks. Clear lines.",
    description:
      "The all-time puzzle classic. Rotate and slide tetrominoes to clear lines without stacking to the top.",
    categories: ["puzzle", "arcade"],
    tags: ["classic", "highscore", "blocks"],
    gradient: "linear-gradient(135deg, #06b6d4 0%, #7c5cff 100%)",
    glyph: "🟦",
    source: "custom",
    controls: ["Arrow Keys", "Space"],
    players: "single",
    featured: true,
    isNew: true,
    rating: 4.8,
    plays: 64_200,
  },
  {
    slug: "minesweeper",
    icon: "game-icons:mining-helmet",
    title: "Minesweeper",
    short: "Reveal cells. Don't hit the bomb.",
    description:
      "The Windows-era classic. Use number clues to deduce which cells are safe and flag the mines.",
    categories: ["puzzle", "strategy"],
    tags: ["classic", "logic"],
    gradient: "linear-gradient(135deg, #1f2937 0%, #ef4444 100%)",
    glyph: "💣",
    source: "custom",
    controls: ["Mouse", "Right-click"],
    players: "single",
    isNew: true,
    rating: 4.5,
    plays: 18_700,
  },
  {
    slug: "breakout",
    icon: "game-icons:brick-wall",
    title: "Breakout",
    short: "Bounce, smash, repeat.",
    description:
      "The arcade brick-breaker. Bounce the ball with your paddle and clear all the bricks.",
    categories: ["arcade", "action"],
    tags: ["classic", "highscore"],
    gradient: "linear-gradient(135deg, #ef4444 0%, #facc15 100%)",
    glyph: "🧱",
    source: "custom",
    controls: ["Arrow Keys", "A/D"],
    players: "single",
    isNew: true,
    rating: 4.4,
    plays: 14_200,
  },
  {
    slug: "asteroids",
    icon: "game-icons:rocket",
    title: "Asteroids",
    short: "Vector-graphics space shooter.",
    description:
      "Pilot your ship through an asteroid field. Rotate, thrust, and shoot to break them apart.",
    categories: ["arcade", "action"],
    tags: ["classic", "shooter", "highscore"],
    gradient: "linear-gradient(135deg, #020118 0%, #7c5cff 100%)",
    glyph: "🚀",
    source: "custom",
    controls: ["Arrow Keys", "Space"],
    players: "single",
    featured: true,
    isNew: true,
    rating: 4.6,
    plays: 22_900,
  },
  {
    slug: "whack-a-mole",
    icon: "game-icons:gavel",
    title: "Whack-a-Mole",
    short: "30 seconds. Bonk every mole.",
    description:
      "Reflex test. Moles pop up at random — click them as fast as you can before time runs out.",
    categories: ["arcade"],
    tags: ["casual", "reflex", "highscore"],
    gradient: "linear-gradient(135deg, #ca8a04 0%, #f97316 100%)",
    glyph: "🐹",
    source: "custom",
    controls: ["Mouse", "Touch"],
    players: "single",
    isNew: true,
    rating: 4.3,
    plays: 9_400,
  },
  {
    slug: "chrome-dino",
    icon: "game-icons:t-rex-skull",
    title: "Chrome Dino",
    short: "The offline runner that's now online.",
    description:
      "Jump cacti and duck pterodactyls in the iconic browser-offline runner. Speed ramps over the first 90 seconds.",
    categories: ["arcade", "action"],
    tags: ["endless", "classic"],
    gradient: "linear-gradient(135deg, #4b5563 0%, #1f2937 100%)",
    glyph: "🦖",
    source: "custom",
    controls: ["Space", "Arrow Keys", "Touch"],
    players: "single",
    rating: 4.6,
    plays: 88_500,
  },
  {
    slug: "wordle",
    icon: "game-icons:scroll-quill",
    title: "Wordy",
    short: "Six guesses, five letters — daily or unlimited.",
    description:
      "Guess the hidden 5-letter word in six tries. Each letter flips to reveal whether it's in the right spot, in the wrong spot, or not in the word at all. Play the daily puzzle (everyone gets the same word) or hit Free Play for unlimited rounds. Stats, streaks, and shareable emoji results included.",
    categories: ["puzzle"],
    tags: ["word", "daily", "logic", "highscore"],
    gradient: "linear-gradient(135deg, #16a34a 0%, #facc15 100%)",
    glyph: "📝",
    source: "custom",
    controls: ["Keyboard", "Mouse", "Touch"],
    players: "single",
    isNew: true,
    rating: 4.7,
    plays: 51_300,
  },
  {
    slug: "sudoku",
    icon: "game-icons:perspective-dice-six",
    title: "Sudoku",
    short: "Fill the 9x9. Easy/Medium/Hard.",
    description:
      "The classic number puzzle. Three difficulty levels, with mistake counter and timer.",
    categories: ["puzzle", "strategy"],
    tags: ["logic", "numbers", "classic"],
    gradient: "linear-gradient(135deg, #1e293b 0%, #7c5cff 100%)",
    glyph: "🔢",
    source: "custom",
    controls: ["Mouse", "Keyboard"],
    players: "single",
    isNew: true,
    featured: true,
    rating: 4.7,
    plays: 38_400,
  },
  {
    slug: "match-three",
    icon: "game-icons:diamonds",
    title: "Gem Match",
    short: "Swap, match, cascade combo.",
    description:
      "Bejeweled-style match-3. Swap gems to line up three or more, trigger cascade combos for huge scores.",
    categories: ["puzzle", "arcade"],
    tags: ["highscore", "casual"],
    gradient: "linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%)",
    glyph: "💎",
    source: "custom",
    controls: ["Mouse", "Touch"],
    players: "single",
    isNew: true,
    rating: 4.6,
    plays: 24_700,
  },
  {
    slug: "tower-of-hanoi",
    icon: "game-icons:stone-tower",
    title: "Tower of Hanoi",
    short: "Stack the disks. Solve in min moves.",
    description:
      "The classic recursive puzzle. Move all disks to the right peg without ever placing a bigger disk on a smaller one.",
    categories: ["puzzle", "strategy"],
    tags: ["logic", "classic"],
    gradient: "linear-gradient(135deg, #16a34a 0%, #06b6d4 100%)",
    glyph: "🗼",
    source: "custom",
    controls: ["Mouse", "Touch"],
    players: "single",
    isNew: true,
    rating: 4.2,
    plays: 7_300,
  },
  {
    slug: "bubble-shooter",
    icon: "game-icons:bubbles",
    title: "Bubble Shooter",
    short: "Aim, fire, pop.",
    description:
      "Match three or more bubbles of the same color to clear them. Don't let the wall reach the bottom.",
    categories: ["puzzle", "arcade"],
    tags: ["highscore", "casual"],
    gradient: "linear-gradient(135deg, #06b6d4 0%, #ef4444 100%)",
    glyph: "🫧",
    source: "custom",
    controls: ["Mouse", "Space"],
    players: "single",
    isNew: true,
    rating: 4.4,
    plays: 16_200,
  },
  {
    slug: "agar-clone",
    icon: "game-icons:bubbling-flask",
    title: "Agar",
    short: "Eat smaller cells. Don't get eaten.",
    description:
      "Steer a cell around an arena, eat pellets and rivals smaller than you, and dodge anything bigger. Bigger cells move slower — being huge is its own risk.",
    categories: ["action", "arcade"],
    tags: ["arcade", "endless", "ai"],
    gradient: "linear-gradient(135deg, #7c5cff 0%, #16a34a 100%)",
    glyph: "🟢",
    source: "custom",
    controls: ["Mouse", "Touch"],
    players: "single",
    rating: 4.5,
    plays: 96_400,
  },
  {
    slug: "slither",
    icon: "game-icons:snake-tongue",
    title: "Slither",
    short: "Eat dots, grow longer, dodge other snakes.",
    description:
      "Drive a snake around an arena, eat glowing pellets to grow, and force AI opponents into your body to take them out. Boost to overtake — but boosting costs length.",
    categories: ["action", "arcade"],
    tags: ["arcade", "endless", "ai"],
    gradient: "linear-gradient(135deg, #facc15 0%, #ef4444 100%)",
    glyph: "🐍",
    source: "custom",
    controls: ["Mouse", "Space"],
    players: "single",
    rating: 4.6,
    plays: 142_000,
  },
  {
    slug: "krunker",
    icon: "game-icons:machine-gun-magazine",
    title: "Krunker",
    short: "Block-style FPS — bots, two guns, one arena.",
    description:
      "Our take on the browser-FPS genre. Drop into a small arena with four bots, sweep them with a pistol or a rifle, dodge their shots. Pointer-locked mouse aim, WASD movement, jump, sprint, reload. 90-second rounds — most kills wins.",
    categories: ["action"],
    tags: ["fps", "shooter", "highscore"],
    gradient: "linear-gradient(135deg, #f59e0b 0%, #1f2937 100%)",
    glyph: "🔫",
    source: "custom",
    controls: ["Mouse", "WASD", "Space"],
    players: "single",
    isNew: true,
    rating: 4.3,
    plays: 73_200,
  },
  {
    slug: "skribbl",
    icon: "game-icons:paint-brush",
    title: "Skribbl",
    short: "Draw and guess with friends — live.",
    description:
      "Real-time draw-and-guess, built natively for Nexplay. Take turns sketching a word while everyone else races to guess it.",
    categories: ["2-player", "puzzle"],
    tags: ["multiplayer", "online", "party", "realtime"],
    gradient: "linear-gradient(135deg, #a855f7 0%, #facc15 100%)",
    glyph: "🎨",
    source: "custom",
    controls: ["Mouse", "Keyboard"],
    players: "multiplayer",
    isNew: true,
    featured: true,
    rating: 4.8,
    plays: 0,
  },
  {
    slug: "geoguessr-clone",
    icon: "game-icons:earth-asia-oceania",
    title: "GeoGuessr",
    short: "Where in the world is this?",
    description:
      "Dropped at a random street view, you have to guess where on Earth you are.",
    categories: ["puzzle", "adventure"],
    tags: ["geography", "single-player"],
    gradient: "linear-gradient(135deg, #06b6d4 0%, #16a34a 100%)",
    glyph: "🌍",
    source: "embed",
    url: "https://geoguessr.com",
    controls: ["Mouse"],
    players: "single",
    rating: 4.6,
    plays: 39_800,
  },
  {
    slug: "agma",
    icon: "game-icons:lightning-storm",
    title: "Agma.io",
    short: "Cell-eater with power-ups.",
    description:
      "An expanded take on the cell-eating genre. Tons of game modes, skins, and power-ups.",
    categories: ["action", "arcade"],
    tags: ["multiplayer", "online"],
    gradient: "linear-gradient(135deg, #ef4444 0%, #facc15 100%)",
    glyph: "⚡",
    source: "embed",
    url: "https://agma.io",
    controls: ["Mouse", "Space"],
    players: "multiplayer",
    rating: 4.2,
    plays: 22_100,
  },
  {
    slug: "doodle-jump",
    icon: "game-icons:cricket-bat",
    title: "Doodle",
    short: "Bounce ever upward through skies and storms.",
    description:
      "A classic vertical jumper, our way. Auto-jump on platforms, ride springs and rockets, dodge purple monsters, and grab coins on the way up. The higher you climb, the meaner the platforms get.",
    categories: ["arcade", "action"],
    tags: ["arcade", "endless", "highscore"],
    gradient: "linear-gradient(135deg, #3aafff 0%, #7c3aed 100%)",
    glyph: "🦗",
    source: "custom",
    controls: ["Arrow Keys", "WASD", "Touch"],
    players: "single",
    isNew: true,
    rating: 4.5,
    plays: 0,
  },
  {
    slug: "diep",
    icon: "game-icons:battle-tank",
    title: "Diep",
    short: "Tank arena: pop polygons, hunt rivals.",
    description:
      "Drive a tank through an arena dotted with rotating polygons. Squares, triangles, and pentagons all award score when you blast them; red rival tanks award a lot more. HP regens after a few seconds out of fire.",
    categories: ["action", "arcade"],
    tags: ["arcade", "endless", "ai"],
    gradient: "linear-gradient(135deg, #3b82f6 0%, #1f2937 100%)",
    glyph: "🚗",
    source: "custom",
    controls: ["Mouse", "WASD", "Space"],
    players: "single",
    rating: 4.5,
    plays: 67_900,
  },
];

export function getGame(slug: string): Game | undefined {
  return GAMES.find((g) => g.slug === slug);
}

export function getCategory(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}

export function gamesByCategory(slug: string): Game[] {
  return GAMES.filter((g) => g.categories.includes(slug));
}

export function featuredGames(): Game[] {
  return GAMES.filter((g) => g.featured);
}

export function newGames(): Game[] {
  return GAMES.filter((g) => g.isNew);
}

export function popularGames(limit = 8): Game[] {
  return [...GAMES].sort((a, b) => b.plays - a.plays).slice(0, limit);
}

export function searchGames(query: string): Game[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return GAMES.filter((g) => {
    return (
      g.title.toLowerCase().includes(q) ||
      g.short.toLowerCase().includes(q) ||
      g.tags.some((t) => t.toLowerCase().includes(q)) ||
      g.categories.some((c) => c.toLowerCase().includes(q))
    );
  });
}
